### ISSUE TITLE
Add initial files to the repository

### ISSUE THREAD

**Issue by bartlomn** [Kesse8401/TicTacToe#1]
As a bare minimum you will need an `index.html` file with some hello world text, and a `README.md` file to store your notes about the project

* create files locally
* init local git repository
* add files to the local repo
* add remote to the local repo
* push to remote

Definition of done:
* basic structure in the html file + some hello world type text
* readme
   * what is this project about
   * what technology you are using and why
   * short paragraph why we don't have tests atm.

**Comment by Kesse8401** [comment]
I added reference to the future external style.css and index.js files

**Comment by bartlomn** [comment]
this has been completed and merged in 35ebd6b. Closing.
