### ISSUE TITLE
Create a function that will create a game tile

### ISSUE THREAD

**Issue by bartlomn** [Kesse8401/TicTacToe#3]
As a developer I need a function that will create an individual game tile for me.

Acceptance criteria:
* Use ES6 notation
* Function should live in a separate JS file 

Definition of done:
* As a developer I can call the function from the scope of html file
* function returns an instance of a HTMLElement
* html element returned is interactive:
   * use appropriate pointer on roll over
   * click on element is reported in the console 
* relevant notes in the readme

**Comment by Kesse8401** [comment]
I committed a bit of code with description of their functionality and some questions that came up.
