### ISSUE TITLE
Create a function that will create a game board

### ISSUE THREAD

**Issue by bartlomn** [Kesse8401/TicTacToe#4]
As a developer I need to create a function that will create a game board on screen. This will be used to draw the board on the first run of the game and upon subsequent game restarts.

Acceptance criteria:
* Use ES6 notation
* Use the `tile function` to create individual tiles
* Function should create a root element and add individual tiles as children

Definition of done:
* Upon calling the function I can see that the HTML elements of the game are added to the page DOM if not present, function does nothing if elements already present

Out of scope:
* Game board styling - we're just interested in displaying the tiles on screen in whatever default format they will appear

**Comment by Kesse8401** [comment]
for loop is in ES5 still - I am working on it. Also - I am not saying it is perfect but I am working on it!

**Comment by bartlomn** [comment]
Closing
